[package]
name = "agentifa-555nake-protocol"
version = "0.3.3"
edition = "2021"

[dependencies]
bevy_ecs = { version = "0.8.1", default-features = false }
naia-shared = { git = "https://github.com/FF-AntiK/naia.git", branch = "ipv6" }
rand = "0.8.5"
